//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Data.Model.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKey
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ApiKey1 { get; set; }
        public string CallerUrl { get; set; }
    }
}
